### ISSUE TITLE
HUD elements are invisible with Knob Control

### ISSUE THREAD

**Issue by UnscathedAnimal** [Flaxbeard/Cyberware#101]
I don't actually know which side is causing this conflict, so I'm mentioning the issue to both mod creators. After playing the Invasion modpack and acquiring the Cyberware Hudjack, I was unable to see my power levels. After quite a lot of removing and adding and swapping mods I eventually narrowed it down to Knob Control. Put it in, HUD disappears. Take it out, HUD returns.

No idea what could be causing that though since I'm entirely unfamiliar with Knob Control, and there are no errors thrown that I'm aware of. Everything apparently works as normal, just without the HUD.

**Comment by UnscathedAnimal** [comment]
Update: after messing around in the configs, it looks like the "remove potion icons" setting in Knob Control is to blame. Changed that to False and the Cyberware HUD stuff shows up again.

Still not sure which side is causing the issue though. Might be this side attaching HUD elements to things they probably shouldn't be, might be Knob Control being too broad in their definition of "potion icons".

Either way, hope this helps.

**Comment by GenDeathrow** [comment]
It seems to be this issue here: https://github.com/Flaxbeard/Cyberware/blob/28a61675f0839b59416a8ab200efbc13ef66754f/src/main/java/flaxbeard/cyberware/common/handler/HudHandler.java#L131

Knob control and a hand full of others mods like potion Icon remover cancel this event all together to not show potions, Its in turn canceling the potion drawing event on Pre, and since yours draws on post it is never called. If you switch it on your side. it will be compatible with other mods that cancel the potion events.
