### ISSUE TITLE
[0.2.3] Metabolic Generator doesn't get along with Saturation

### ISSUE THREAD

**Issue by Alaberti** [Flaxbeard/Cyberware#57]
I have an RFTools environmental controller set to provide Saturation III in an area, or in some places a blood magic ritual to do the same. I get the benefits of saturation, however, the food shanks continue to decrease as energy is consumed. You cannot eat because the game knows you're getting saturation, but you will die of starvation.

Relogging does reset the food counter and the process starts all over again.

**Comment by S-Fort** [comment]
Just informing you that the best way of fixing this is blocking the saturation effect when you have the metabolic generator on. And is probably what is going to end up happening. So until this issue is addressed i suggest doing what you probably will have to and that being removing one of the two.

**Comment by Flaxbeard** [comment]
https://minecraft.curseforge.com/projects/cyberware/files/2353466

**Comment by Veggetossj** [comment]
Could you please explain how the Metabolic Generator works? I have it installed and the tooltip says: 'Uses calories to produce energy' Yet neither running around nor eating generates power.

**Comment by LatentDesire** [comment]
Veggetossj, not sure this is the place to ask for clarification unless you're fairly certain that it due to a bug. 

To answer your question though, the Metabolic Generator works using some of your stored calories to generate power. In game terms, it increases the rate in which you will lose hunger pops. This happens at a slower rate than say the vanilla hunger effect, but you'll likely need to eat slightly more often throughout the day than you would without it. 

Assuming you are using either cybereyes with the HUD jack addon, or the (I believe it's called) HUD lense in order to view your stored power, there may be a few reasons as to why you are not generating power. 

First of all, have you also installed a battery(s) to store your power? If you have, was it the dense battery? This battery would be stored in the same area as the metabolic generator, if memory serves. Said battery is only able to be charged by standing on a powered charger block. Other methods of power production are incapable of charging this dense battery. If I remember correctly, there are two other kind of batteries that can be charged by installed augments. One that can be installed in the bone section of your body, and another that can be installed in the same body area as the dense battery. 

Finally, have you ensured that the power production of all installed augments exceeds the power usage of installed augments. If the drain is larger than what is being produced, depending on the installed augments, you may be able to power down one or more augments to allow power production's surplus power to fill your batteries. Please check your key bindings to learn or remap the key that will allow you to toggle your augments. (The exact name eludes me at the moment but should be easy to figure out.)

**Comment by Veggetossj** [comment]
I had just the metabolic generator installed, which by itself only had 25 power capacity and thusly it didnt generate power for my cybereyes. After installing some marrow batteries it did generate power.

Thanks for clearing it up for me.
