### ISSUE TITLE
Cannot install Hudlens.

### ISSUE THREAD

**Issue by Apocryphai** [Flaxbeard/Cyberware#86]
In the Robosurgeon, whenever I try to install a Salvaged Hudlens the icon slot where the Salvaged Cybereyes are installed (I can't actualy see them, I have the invisible icons bug too) gets a red flash border around it and it won't let me install the Hudlens.

I have plenty of power supply and I have replaced my human eyes with Cybereyes. If I remove the Cybereyes it will let me put the Hudlens in that slot but of course that renders me blind. 

This is with Cyberware beta 0.2.6 in a modified AllTheMods pack on 1.10.2. Am I doing something wrong?

**Comment by LatentDesire** [comment]
*face palm*
Hudlens serve the same function as cyber eyes with the the hud module. (Forget if that's the exact name. Just woke up.)

They are basically tier 0 cyber eyes that you can't upgrade by adding more modules. 

Functionality they're contact lenses that show a heads up display. That's why you can't replace your eyes with them. If you have no need for any other modules on your eyes other than HUD (night vision for example), putting back in your human eyes with HUD lens in a slot next to it would be more ideal for you.

**Comment by Apocryphai** [comment]
Ahhh I see, my bad! Thanks for explaning :)
